[tool.poetry]
name = "enochecker_test"
version = "0.9.0"
description = "Library to help testing checker scripts based on enochecker"
authors = ["ldruschk <ldrushk@posteo.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/enowars/enochecker_test"
repository = "https://github.com/enowars/enochecker_test"
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",
    # Indicate who your project is intended for
    # 'Intended Audience :: Developers',
    "License :: OSI Approved :: MIT License",
    # Specify the Python versions you support here. In particular, ensure
    # that you indicate whether you support Python 2, Python 3 or both.
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = "^3.11"
certifi = "^2023.5.7"
charset-normalizer = "^3.1.0"
enochecker-core = "^0.10.0"
exceptiongroup = "^1.1.1"
idna = "^3.4"
iniconfig = "^2.0.0"
jsons = "^1.6.3"
packaging = "^23.1"
pluggy = "^1.0.0"
pytest = "^7.3.1"
requests = "^2.30.0"
tomli = "^2.0.1"
typish = "^1.9.3"
urllib3 = "^2.0.2"

[tool.poetry.group.test.dependencies]
appdirs = "^1.4.4"
black = "^23.3.0"
click = "^8.1.3"
flake8 = "^6.0.0"
isort = "^5.8.0"
mccabe = "^0.7.0"
mypy = "^1.3.0"
mypy-extensions = "^1.0.0"
pathspec = "^0.9.0"
platformdirs = "^2.4.0"
pycodestyle = "^2.10.0"
pyflakes = "^3.0.1"
regex = "^2023.5.5"
toml = "^0.10.2"
#tomli = "^1.2.2"
typed-ast = "^1.5.4"
types-colorama = "^0.4.15.11"
types-docutils = "^0.20.0.1"
types-Pygments = "^2.15.0.1"
types-requests = "^2.30.0.0"
types-setuptools = "^67.7.0.2"
types-toml = "^0.10.8.6"
types-urllib3 = "^1.26.25.13"
typing_extensions = "^4.0.0"


[tool.poetry.scripts]
enochecker_cli = "enochecker_cli.main:main"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"


[tool.mypy]
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "enochecker"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "enochecker_core"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jsons"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "enochecker_test"

[tool.isort]
multi_line_output=3
include_trailing_comma = true
line_length = 88
force_grid_wrap = 0
use_parentheses = true
